import {
  BP_STUDIO_SPEC_SCHEMA_VERSION,
  type BPStudioAdapterSpec,
} from "./bp-studio-spec.ts";

export function simpleQuadrupedBPStudioSpec(seed: number): BPStudioAdapterSpec {
  const nodes: BPStudioAdapterSpec["tree"]["nodes"] = [
    { id: "root", kind: "root", label: "root" },
    { id: "front-hub", kind: "body", label: "front hub", tags: ["torso", "hub"] },
    { id: "rear-hub", kind: "body", label: "rear hub", tags: ["torso", "hub"] },
    { id: "head", kind: "flap", label: "head", tags: ["terminal"] },
    { id: "tail", kind: "flap", label: "tail", tags: ["terminal"] },
    { id: "front-left-leg", kind: "flap", label: "front left leg", tags: ["terminal", "leg"] },
    { id: "front-right-leg", kind: "flap", label: "front right leg", tags: ["terminal", "leg"] },
    { id: "rear-left-leg", kind: "flap", label: "rear left leg", tags: ["terminal", "leg"] },
    { id: "rear-right-leg", kind: "flap", label: "rear right leg", tags: ["terminal", "leg"] },
  ];
  const treeEdges: BPStudioAdapterSpec["tree"]["edges"] = [
    { id: "root-front-hub", from: "root", to: "front-hub", length: 0, role: "body", width: 1 },
    { id: "front-head", from: "front-hub", to: "head", length: 1, role: "appendage", width: 1 },
    { id: "front-left-leg", from: "front-hub", to: "front-left-leg", length: 1, role: "appendage", width: 1 },
    { id: "front-right-leg", from: "front-hub", to: "front-right-leg", length: 1, role: "appendage", width: 1 },
    { id: "front-rear-river", from: "front-hub", to: "rear-hub", length: 2, role: "river", width: 1 },
    { id: "rear-left-leg", from: "rear-hub", to: "rear-left-leg", length: 1, role: "appendage", width: 1 },
    { id: "rear-right-leg", from: "rear-hub", to: "rear-right-leg", length: 1, role: "appendage", width: 1 },
    { id: "rear-tail", from: "rear-hub", to: "tail", length: 3, role: "appendage", width: 1 },
  ];
  const riverHints = [
    ["front-head", "front-hub", "head", "vertical"],
    ["front-left-leg", "front-hub", "front-left-leg", "horizontal"],
    ["front-right-leg", "front-hub", "front-right-leg", "horizontal"],
    ["front-rear-river", "front-hub", "rear-hub", "vertical"],
    ["rear-left-leg", "rear-hub", "rear-left-leg", "horizontal"],
    ["rear-right-leg", "rear-hub", "rear-right-leg", "horizontal"],
    ["rear-tail", "rear-hub", "tail", "vertical"],
  ] as const;
  const flapPlacements: BPStudioAdapterSpec["layout"]["flaps"] = [
    {
      nodeId: "head",
      label: "head",
      class: "terminal",
      terminal: { x: 16, y: 25 },
      side: "top",
      width: 0,
      height: 0,
      elevation: 0,
      terminalRadius: 1,
      priority: 1,
    },
    {
      nodeId: "front-left-leg",
      label: "front left leg",
      class: "terminal",
      terminal: { x: 12, y: 21 },
      side: "left",
      width: 0,
      height: 0,
      elevation: 0,
      terminalRadius: 1,
      priority: 2,
      mirroredWith: "front-right-leg",
    },
    {
      nodeId: "front-right-leg",
      label: "front right leg",
      class: "terminal",
      terminal: { x: 20, y: 21 },
      side: "right",
      width: 0,
      height: 0,
      elevation: 0,
      terminalRadius: 1,
      priority: 3,
      mirroredWith: "front-left-leg",
    },
    {
      nodeId: "rear-left-leg",
      label: "rear left leg",
      class: "terminal",
      terminal: { x: 12, y: 12 },
      side: "left",
      width: 0,
      height: 0,
      elevation: 0,
      terminalRadius: 1,
      priority: 4,
      mirroredWith: "rear-right-leg",
    },
    {
      nodeId: "rear-right-leg",
      label: "rear right leg",
      class: "terminal",
      terminal: { x: 20, y: 12 },
      side: "right",
      width: 0,
      height: 0,
      elevation: 0,
      terminalRadius: 1,
      priority: 5,
      mirroredWith: "rear-left-leg",
    },
    {
      nodeId: "tail",
      label: "tail",
      class: "terminal",
      terminal: { x: 16, y: 5 },
      side: "bottom",
      width: 0,
      height: 0,
      elevation: 0,
      terminalRadius: 3,
      priority: 6,
    },
  ];
  return {
    schemaVersion: BP_STUDIO_SPEC_SCHEMA_VERSION,
    id: `simple-animal-${seed}`,
    seed,
    archetype: "quadruped",
    expectedComplexity: {
      bucket: "small",
      targetFlaps: [6, 6],
      targetTreeEdges: [8, 8],
      targetCreases: [80, 220],
      expectedGridSize: [16, 32],
    },
    sheet: {
      width: 32,
      height: 32,
      gridSize: 32,
      margin: 1,
      coordinateSystem: "integer-grid",
      unit: "bp-grid",
    },
    tree: {
      rootId: "root",
      nodes,
      edges: treeEdges,
    },
    layout: {
      symmetry: "bilateral-x",
      bodies: [
        { nodeId: "front-hub", label: "front hub", center: { x: 16, y: 21 }, width: 2, height: 2, elevation: 0, tags: ["torso", "hub"] },
        { nodeId: "rear-hub", label: "rear hub", center: { x: 16, y: 12 }, width: 2, height: 2, elevation: 0, tags: ["torso", "hub"] },
      ],
      flaps: flapPlacements,
      rivers: riverHints.map(([id, from, to, preferredAxis]) => ({
        edgeId: id,
        from,
        to,
        width: 2,
        preferredAxis,
        bend: preferredAxis === "horizontal" ? "direct" : "dogleg",
        clearance: 1,
      })),
      optimizerHints: {
        objective: "compact-flaps",
        keepSymmetry: false,
        allowTerminalRelaxation: true,
        maxIterations: 5000,
        topK: 5,
      },
    },
    sampler: {
      samplerVersion: "bp-studio-sampler/v1",
      grammar: "debug-simple-animal",
      seed,
      variation: seed,
      symmetry: "bilateral-x",
      notes: ["Debug fixture: body, head, tail, and four legs only."],
    },
  };
}
