import ear from "rabbit-ear";
import { countCreases, normalizeFold } from "./fold-utils.ts";
import { SeededRandom } from "./random.ts";
import type {
  EdgeAssignment,
  FOLDFormat,
  GenerationConfig,
  LabelPolicy,
  RabbitEarFoldProgramAxiom,
  RabbitEarFoldProgramMetadata,
} from "./types.ts";

type Line = { vector: [number, number]; origin: [number, number] };

export function generateRabbitEarFoldProgram(config: GenerationConfig): FOLDFormat {
  const minActive = config.numCreases;
  const maxActive = Math.max(minActive, config.maxCreases ?? minActive);
  const rng = new SeededRandom(config.seed);
  let best: FOLDFormat | undefined;
  let lastError = "no candidate";

  for (let attempt = 0; attempt < 24; attempt++) {
    try {
      const candidate = generateCandidate(config, new SeededRandom(config.seed + attempt * 104729), minActive, maxActive);
      if (isBetterCandidate(candidate, best, minActive, maxActive)) best = candidate;
      if (candidateActiveCreases(candidate) >= minActive && candidateActiveCreases(candidate) <= maxActive) {
        return candidate;
      }
      lastError = `active crease count ${candidateActiveCreases(candidate)} is outside ${minActive}-${maxActive}`;
    } catch (error) {
      lastError = error instanceof Error ? error.message : String(error);
      // Step the outer RNG so repeated internal failures do not produce the same
      // candidate sequence if future code reuses this generator.
      rng.next();
    }
  }

  if (best) return best;
  throw new Error(`Rabbit Ear fold-program generator failed: ${lastError}`);
}

function generateCandidate(config: GenerationConfig, rng: SeededRandom, minActive: number, maxActive: number): FOLDFormat {
  const graph = ear.graph.square() as FOLDFormat;
  const axiomUsage: Partial<Record<RabbitEarFoldProgramAxiom, number>> = {};
  const targetActiveCreases = rng.int(minActive, maxActive);
  const maxFoldOps = Math.min(96, Math.max(18, Math.ceil(targetActiveCreases / 4)));
  const maxAttempts = maxFoldOps * 24;
  let appliedFoldCount = 0;
  let attemptedFoldCount = 0;

  for (let i = 0; i < maxAttempts && candidateActiveCreases(graph) < targetActiveCreases; i++) {
    attemptedFoldCount += 1;
    const before = JSON.parse(JSON.stringify(graph)) as FOLDFormat;
    try {
      const { line, axiom } = randomAxiomLine(rng);
      const assignment: EdgeAssignment = rng.next() < 0.5 ? "M" : "V";
      ear.graph.flatFold(graph, line.vector, line.origin, assignment);
      axiomUsage[axiom] = (axiomUsage[axiom] ?? 0) + 1;
      appliedFoldCount += 1;
      if ((graph.edges_vertices?.length ?? 0) > maxActive * 5 + 80) break;
    } catch {
      for (const key of Object.keys(graph)) delete graph[key];
      Object.assign(graph, before);
    }
  }

  const metadata: RabbitEarFoldProgramMetadata = {
    generator: "rabbit-ear-fold-program",
    rabbitEarApi: "ear.graph.flatFold",
    appliedFoldCount,
    attemptedFoldCount,
    axiomUsage,
    activeCreaseCount: candidateActiveCreases(graph),
    targetActiveCreases,
    targetActiveCreaseRange: [minActive, maxActive],
    requestedBucket: config.bucket,
  };
  const labelPolicy: LabelPolicy = {
    labelSource: "rabbit-ear-fold-program",
    geometrySource: "rabbit-ear-fold-program",
    assignmentSource: "rabbit-ear-fold-program",
    trainingEligible: true,
    notes: ["Supplemental strict non-BP fold-program sample generated by Rabbit Ear flatFold operations."],
  };

  const normalized = normalizeFold(
    {
      ...graph,
      rabbit_ear_metadata: metadata,
      density_metadata: {
        densityBucket: config.bucket,
        gridSize: 0,
        targetEdgeRange: [minActive, maxActive],
        subfamily: "rabbit-ear-fold-program",
        symmetry: "none",
        generatorSteps: ["rabbit-ear-axiom-line", "ear.graph.flatFold", "strict-rabbit-ear-validation"],
        moleculeCounts: {
          sourceFold: appliedFoldCount,
        },
      },
      label_policy: labelPolicy,
    },
    "cp-synthetic-generator/rabbit-ear-fold-program",
  );
  normalized.rabbit_ear_metadata = {
    ...metadata,
    activeCreaseCount: candidateActiveCreases(normalized),
  };
  return normalized;
}

function randomAxiomLine(rng: SeededRandom): { line: Line; axiom: RabbitEarFoldProgramAxiom } {
  const point = (): [number, number] => [rng.float(0.06, 0.94), rng.float(0.06, 0.94)];
  const line = (): Line => ({
    origin: point(),
    vector: normalize([rng.float(-1, 1), rng.float(-1, 1)]),
  });

  const choice = rng.next();
  if (choice < 0.36) return { axiom: "axiom1", line: firstLine(ear.axiom.axiom1(point(), point())) };
  if (choice < 0.66) return { axiom: "axiom2", line: firstLine(ear.axiom.axiom2(point(), point())) };
  if (choice < 0.84) return { axiom: "axiom3", line: firstLine(ear.axiom.axiom3(line(), line())) };
  if (choice < 0.94) return { axiom: "axiom4", line: firstLine(ear.axiom.axiom4(line(), point())) };
  return { axiom: "axiom7", line: firstLine(ear.axiom.axiom7(line(), line(), point())) };
}

function firstLine(result: unknown): Line {
  const line = Array.isArray(result) ? result[0] : result;
  if (!line || typeof line !== "object") throw new Error("Rabbit Ear axiom did not return a fold line");
  const maybeLine = line as Partial<Line>;
  if (!maybeLine.vector || !maybeLine.origin) throw new Error("Rabbit Ear axiom returned an invalid fold line");
  return {
    vector: normalize(maybeLine.vector),
    origin: [maybeLine.origin[0], maybeLine.origin[1]],
  };
}

function normalize(vector: readonly number[]): [number, number] {
  const length = Math.hypot(vector[0], vector[1]);
  if (length < 1e-9) return [1, 0];
  return [vector[0] / length, vector[1] / length];
}

function candidateActiveCreases(fold: FOLDFormat): number {
  return (fold.edges_assignment ?? []).filter((assignment) => assignment === "M" || assignment === "V").length;
}

function isBetterCandidate(candidate: FOLDFormat, current: FOLDFormat | undefined, minActive: number, maxActive: number): boolean {
  if (!current) return true;
  const candidateActive = candidateActiveCreases(candidate);
  const currentActive = candidateActiveCreases(current);
  const candidateDistance = rangeDistance(candidateActive, minActive, maxActive);
  const currentDistance = rangeDistance(currentActive, minActive, maxActive);
  if (candidateDistance !== currentDistance) return candidateDistance < currentDistance;
  return countCreases(candidate) > countCreases(current);
}

function rangeDistance(value: number, min: number, max: number): number {
  if (value < min) return min - value;
  if (value > max) return value - max;
  return 0;
}
