#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PYTHON="${PYTHON:-.venv/bin/python}"
MANIFEST="${MANIFEST:-data/generated/synthetic/cp_training_mix_v1/raw-manifest.jsonl}"
OUTPUT_ROOT="${OUTPUT_ROOT:-checkpoints/runpod_v2_continuation}"
INIT_CHECKPOINT="${INIT_CHECKPOINT:-checkpoints/runpod_phase3_curriculum/stage-balanced/latest.pt}"
DEVICE="${DEVICE:-cuda}"
BACKBONE="${BACKBONE:-hrnet_w18}"
HIDDEN_CHANNELS="${HIDDEN_CHANNELS:-128}"
BATCHNORM_MODE="${BATCHNORM_MODE:-batch-stats}"
IMAGE_SIZE="${IMAGE_SIZE:-1024}"
MAX_EDGES="${MAX_EDGES:-300}"
TRAIN_FAMILY_SAMPLING="${TRAIN_FAMILY_SAMPLING:-balanced}"
BATCH_SIZE="${BATCH_SIZE:-1}"
NUM_WORKERS="${NUM_WORKERS:-4}"
LR="${LR:-0.0002}"
SEED="${SEED:-17}"
LOG_EVERY="${LOG_EVERY:-50}"
SKIP_GRAPH_EVAL="${SKIP_GRAPH_EVAL:-1}"
EVAL_THRESHOLDS="${EVAL_THRESHOLDS:-0.35,0.45,0.55,0.65,0.75,0.85}"

PROFILE="${PROFILE:-v2-all-issue-mix}"
EVAL_PROFILE="${EVAL_PROFILE:-$PROFILE}"
TRAIN_COUNT_WARMUP="${TRAIN_COUNT_WARMUP:-512}"
VAL_COUNT_WARMUP="${VAL_COUNT_WARMUP:-64}"
STEPS_WARMUP="${STEPS_WARMUP:-1200}"
TRAIN_COUNT_FULL="${TRAIN_COUNT_FULL:-2048}"
VAL_COUNT_FULL="${VAL_COUNT_FULL:-256}"
STEPS_FULL="${STEPS_FULL:-4800}"
RUN_FULL="${RUN_FULL:-1}"

LINE_HARD_NEGATIVE_WEIGHT="${LINE_HARD_NEGATIVE_WEIGHT:-0.25}"
LINE_HARD_NEGATIVE_RATIO="${LINE_HARD_NEGATIVE_RATIO:-0.05}"
LINE_HARD_NEGATIVE_MULTIPLIER="${LINE_HARD_NEGATIVE_MULTIPLIER:-4.0}"
NON_CREASE_WEIGHT="${NON_CREASE_WEIGHT:-0.1}"
LINE_STYLE_WEIGHT="${LINE_STYLE_WEIGHT:-0.1}"
BOUNDARY_CONTACT_WEIGHT="${BOUNDARY_CONTACT_WEIGHT:-0.75}"
BOUNDARY_CONTACT_POS_WEIGHT="${BOUNDARY_CONTACT_POS_WEIGHT:-12}"
BOUNDARY_CONTACT_CORNER_NEGATIVE_WEIGHT="${BOUNDARY_CONTACT_CORNER_NEGATIVE_WEIGHT:-4}"
BOUNDARY_CONTACT_HARD_NEGATIVE_WEIGHT="${BOUNDARY_CONTACT_HARD_NEGATIVE_WEIGHT:-0.2}"
BOUNDARY_CONTACT_HARD_NEGATIVE_RATIO="${BOUNDARY_CONTACT_HARD_NEGATIVE_RATIO:-0.02}"
BOUNDARY_CONTACT_HARD_NEGATIVE_MULTIPLIER="${BOUNDARY_CONTACT_HARD_NEGATIVE_MULTIPLIER:-8}"
BOUNDARY_CONTACT_HARD_NEGATIVE_MIN_PIXELS="${BOUNDARY_CONTACT_HARD_NEGATIVE_MIN_PIXELS:-256}"
VERTEX_TYPE_WEIGHT="${VERTEX_TYPE_WEIGHT:-0.5}"
VERTEX_TYPE_CLASS_WEIGHTS="${VERTEX_TYPE_CLASS_WEIGHTS:-0.02,10,10,2}"
VERTEX_TYPE_FOCAL_GAMMA="${VERTEX_TYPE_FOCAL_GAMMA:-2.0}"
BOUNDARY_SIDE_WEIGHT="${BOUNDARY_SIDE_WEIGHT:-0.0}"
BOUNDARY_OFFSET_WEIGHT="${BOUNDARY_OFFSET_WEIGHT:-0.0}"
BOUNDARY_COORD_WEIGHT="${BOUNDARY_COORD_WEIGHT:-0.2}"

mkdir -p "$OUTPUT_ROOT"

run_stage() {
  local stage_name="$1"
  local steps="$2"
  local train_count="$3"
  local val_count="$4"
  local output_dir="$5"
  local init_checkpoint="$6"
  local args=(
    scripts/training/train_cpline_smoke.py
    --device "$DEVICE"
    --backbone "$BACKBONE"
    --hidden-channels "$HIDDEN_CHANNELS"
    --batchnorm-mode "$BATCHNORM_MODE"
    --manifest "$MANIFEST"
    --output-dir "$output_dir"
    --image-size "$IMAGE_SIZE"
    --train-count "$train_count"
    --val-count "$val_count"
    --max-edges "$MAX_EDGES"
    --train-family-sampling "$TRAIN_FAMILY_SAMPLING"
    --max-steps "$steps"
    --batch-size "$BATCH_SIZE"
    --num-workers "$NUM_WORKERS"
    --lr "$LR"
    --seed "$SEED"
    --log-every "$LOG_EVERY"
    --augment-profile "$PROFILE"
    --eval-augment-profile "$EVAL_PROFILE"
    --eval-thresholds "$EVAL_THRESHOLDS"
    --line-hard-negative-weight "$LINE_HARD_NEGATIVE_WEIGHT"
    --line-hard-negative-ratio "$LINE_HARD_NEGATIVE_RATIO"
    --line-hard-negative-multiplier "$LINE_HARD_NEGATIVE_MULTIPLIER"
    --v2-heads
    --non-crease-weight "$NON_CREASE_WEIGHT"
    --line-style-weight "$LINE_STYLE_WEIGHT"
    --boundary-contact-weight "$BOUNDARY_CONTACT_WEIGHT"
    --boundary-contact-pos-weight "$BOUNDARY_CONTACT_POS_WEIGHT"
    --boundary-contact-corner-negative-weight "$BOUNDARY_CONTACT_CORNER_NEGATIVE_WEIGHT"
    --boundary-contact-hard-negative-weight "$BOUNDARY_CONTACT_HARD_NEGATIVE_WEIGHT"
    --boundary-contact-hard-negative-ratio "$BOUNDARY_CONTACT_HARD_NEGATIVE_RATIO"
    --boundary-contact-hard-negative-multiplier "$BOUNDARY_CONTACT_HARD_NEGATIVE_MULTIPLIER"
    --boundary-contact-hard-negative-min-pixels "$BOUNDARY_CONTACT_HARD_NEGATIVE_MIN_PIXELS"
    --vertex-type-weight "$VERTEX_TYPE_WEIGHT"
    --vertex-type-class-weights "$VERTEX_TYPE_CLASS_WEIGHTS"
    --vertex-type-focal-gamma "$VERTEX_TYPE_FOCAL_GAMMA"
    --boundary-side-weight "$BOUNDARY_SIDE_WEIGHT"
    --boundary-offset-weight "$BOUNDARY_OFFSET_WEIGHT"
    --boundary-coord-weight "$BOUNDARY_COORD_WEIGHT"
    --use-v2-observed-assignment
    --init-checkpoint "$init_checkpoint"
  )
  if [[ "$SKIP_GRAPH_EVAL" == "1" ]]; then
    args+=(--skip-graph-eval)
  fi
  mkdir -p "$output_dir"
  local log_path="$output_dir/train.log"
  echo "=== Running $stage_name ($PROFILE) -> $output_dir ===" | tee "$log_path"
  TQDM_DISABLE="${TQDM_DISABLE:-1}" "$PYTHON" "${args[@]}" 2>&1 | tee -a "$log_path"
}

run_stage "warmup" "$STEPS_WARMUP" "$TRAIN_COUNT_WARMUP" "$VAL_COUNT_WARMUP" "$OUTPUT_ROOT/warmup" "$INIT_CHECKPOINT"

if [[ "$RUN_FULL" == "1" ]]; then
  run_stage "full" "$STEPS_FULL" "$TRAIN_COUNT_FULL" "$VAL_COUNT_FULL" "$OUTPUT_ROOT/full" "$OUTPUT_ROOT/warmup/latest.pt"
fi
