#!/usr/bin/env python3
"""Run V2.0 issue-slice ablations against the synthetic issue benchmark."""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from collections.abc import Iterable
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")

import cv2
import numpy as np
import torch
from PIL import Image, ImageDraw, ImageFont
from scipy.optimize import linear_sum_assignment

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from src.inference.pipeline import (  # noqa: E402
    DEFAULT_CHECKPOINT,
    DEFAULT_CHECKPOINT_MANIFEST,
    build_stage4_builder,
    load_checkpoint_manifest,
    load_cpline_model,
    select_device,
    verify_checkpoint_file,
)
from src.models.batchnorm import BATCHNORM_MODES, model_eval_with_batchnorm_mode  # noqa: E402
from src.vectorization import (  # noqa: E402
    AttributedPlanarGraph,
    EdgeAssignmentConfig,
    PlanarGraphBuilder,
    PlanarGraphResult,
    QualityReportConfig,
    RepairAction,
    RepairConfig,
    VectorizerEvidence,
    attribute_graph_from_logits,
    build_quality_report,
    conservative_repair,
    evaluate_graph,
)
from src.vectorization.edge_assignment import assignments_from_existing_result  # noqa: E402
from src.vectorization.evidence import render_vectorizer_evidence_from_pixels  # noqa: E402
from src.vectorization.metrics import (  # noqa: E402
    GraphMetrics,
    match_vertices,
    metrics_from_results,
)

ARTIFACT_ISSUES = {
    "text_false_positive",
    "watermark_false_positive",
    "guide_grid_false_positive",
}
ASSIGNMENT_COLORS = {
    0: (225, 29, 72),
    1: (37, 99, 235),
    2: (17, 24, 39),
    3: (107, 114, 128),
}


@dataclass(frozen=True)
class TargetGraph:
    vertices: np.ndarray
    edges: np.ndarray
    assignments: np.ndarray
    image_size: int


@dataclass(frozen=True)
class SquareFrame:
    x_min: float
    y_min: float
    x_max: float
    y_max: float


@dataclass(frozen=True)
class ModelPrediction:
    line_prob: np.ndarray
    angle: np.ndarray
    junction_heatmap: np.ndarray
    assignment_logits: torch.Tensor


@dataclass(frozen=True)
class VariantResult:
    graph: AttributedPlanarGraph
    status: str
    warning_codes: list[str]
    repair_codes: list[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("visualizations/v2_issue_benchmark/manifest.json"),
        help="Synthetic V2 issue benchmark manifest generated by generate_issue_benchmark.py.",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("visualizations/v2_issue_ablation"))
    parser.add_argument("--checkpoint", type=Path, default=DEFAULT_CHECKPOINT)
    parser.add_argument("--checkpoint-manifest", type=Path, default=DEFAULT_CHECKPOINT_MANIFEST)
    parser.add_argument("--device", choices=["auto", "mps", "cuda", "cpu"], default="auto")
    parser.add_argument("--threshold", type=float, default=None)
    parser.add_argument("--batchnorm-mode", choices=BATCHNORM_MODES, default="batch-stats")
    parser.add_argument("--image-size", type=int, default=None)
    parser.add_argument("--max-examples", type=int, default=None)
    parser.add_argument("--max-visuals-per-issue", type=int, default=1)
    parser.add_argument("--infer-assignments", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest_path = resolve_path(args.manifest)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    benchmark_root = manifest_path.parent
    source_image_size = int(manifest["image_size"])
    image_size = int(args.image_size or source_image_size)

    output_dir = resolve_path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    examples_dir = output_dir / "examples"
    examples_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_manifest_path = resolve_path(args.checkpoint_manifest)
    checkpoint_manifest = load_checkpoint_manifest(checkpoint_manifest_path)
    threshold = float(
        args.threshold
        if args.threshold is not None
        else (checkpoint_manifest.get("inference") or {}).get("vectorizerThreshold", 0.65)
    )
    checkpoint = resolve_path(args.checkpoint)
    verify_checkpoint_file(checkpoint, checkpoint_manifest)
    device = select_device(args.device)
    model = load_cpline_model(checkpoint, device)

    builder = build_stage4_builder(image_size, threshold)
    assignment_config = EdgeAssignmentConfig()
    repair_config = RepairConfig(image_size=image_size)
    report_config = QualityReportConfig(image_size=image_size)

    rows: list[dict[str, Any]] = []
    metric_items: list[tuple[str, str, GraphMetrics]] = []
    visual_items: list[dict[str, Any]] = []
    visual_counts: Counter[str] = Counter()

    for row_index, example in enumerate(manifest["examples"]):
        if args.max_examples is not None and row_index >= args.max_examples:
            break
        issue = str(example["issue"])
        sample_id = str(example["id"])
        target = load_target_graph(benchmark_root, example, source_image_size, image_size)
        clean = load_rgb(benchmark_root / example["clean_image"], image_size=image_size)
        issue_image = load_rgb(benchmark_root / example["issue_image"], image_size=image_size)
        artifact_mask = load_artifact_mask(
            benchmark_root,
            example,
            issue=issue,
            image_size=image_size,
        )

        with model_eval_with_batchnorm_mode(model, batchnorm_mode=args.batchnorm_mode):
            clean_prediction = run_model(model, clean, device)
            issue_prediction = run_model(model, issue_image, device)

        variants: dict[str, tuple[VariantResult, np.ndarray]] = {}
        variants["clean_reference_model"] = (
            build_model_variant(
                clean_prediction,
                builder=builder,
                assignment_config=assignment_config,
                repair_config=repair_config,
                report_config=report_config,
                infer_assignments=args.infer_assignments,
            ),
            clean,
        )
        baseline = build_model_variant(
            issue_prediction,
            builder=builder,
            assignment_config=assignment_config,
            repair_config=repair_config,
            report_config=report_config,
            infer_assignments=args.infer_assignments,
        )
        variants["issue_baseline_model"] = (baseline, issue_image)

        if artifact_mask is not None:
            suppression_mask = artifact_mask & ~target_line_mask(target)
            masked_prediction = mask_artifact_evidence(issue_prediction, suppression_mask)
            variants["artifact_mask_oracle"] = (
                build_model_variant(
                    masked_prediction,
                    builder=builder,
                    assignment_config=assignment_config,
                    repair_config=repair_config,
                    report_config=report_config,
                    infer_assignments=args.infer_assignments,
                    extra_repair_code="oracle_artifact_mask",
                ),
                issue_image,
            )

        variants["oracle_border_chain"] = (
            build_graph_variant(
                apply_oracle_border_chain(
                    baseline.graph,
                    target=target,
                    image_size=image_size,
                ),
                report_config=report_config,
                extra_repair_code="oracle_border_chain",
            ),
            issue_image,
        )
        variants["oracle_assignments"] = (
            build_graph_variant(
                apply_oracle_assignments(
                    baseline.graph,
                    target=target,
                    image_size=image_size,
                ),
                report_config=report_config,
                extra_repair_code="oracle_assignments",
            ),
            issue_image,
        )
        variants["oracle_vector_evidence"] = (
            build_oracle_evidence_variant(
                target,
                builder=builder,
                repair_config=repair_config,
                report_config=report_config,
            ),
            issue_image,
        )
        variants["oracle_topology"] = (
            build_graph_variant(
                oracle_topology_graph(target),
                report_config=report_config,
                extra_repair_code="oracle_topology",
            ),
            issue_image,
        )

        overlay_paths: dict[str, Path] = {}
        for variant, (variant_result, image) in variants.items():
            metrics_obj, output_row = evaluate_variant(
                variant_result,
                target=target,
                example=example,
                variant=variant,
                threshold=threshold,
                artifact_mask=artifact_mask,
            )
            rows.append(output_row)
            metric_items.append((issue, variant, metrics_obj))
            if visual_counts[issue] < args.max_visuals_per_issue:
                overlay_path = examples_dir / issue / sample_id / f"{variant}.png"
                write_graph_overlay(
                    overlay_path,
                    image,
                    variant_result.graph,
                    label=f"{issue} / {sample_id} / {variant}",
                )
                overlay_paths[variant] = overlay_path

        if visual_counts[issue] < args.max_visuals_per_issue:
            input_path = examples_dir / issue / sample_id / "issue_image.png"
            target_path = examples_dir / issue / sample_id / "target_overlay.png"
            input_path.parent.mkdir(parents=True, exist_ok=True)
            Image.fromarray(issue_image).save(input_path)
            write_graph_overlay(
                target_path,
                issue_image,
                oracle_topology_graph(target),
                label=f"{issue} / {sample_id} / target",
            )
            visual_items.append(
                {
                    "issue": issue,
                    "id": sample_id,
                    "issue_image": input_path,
                    "target": target_path,
                    **overlay_paths,
                }
            )
            visual_counts[issue] += 1

        print(json.dumps({"id": sample_id, "issue": issue, "variants": len(variants)}), flush=True)

    summary = build_summary(
        rows,
        metric_items,
        manifest_path=manifest_path,
        checkpoint=checkpoint,
        checkpoint_manifest=checkpoint_manifest_path,
        checkpoint_id=checkpoint_manifest.get("id"),
        image_size=image_size,
        source_image_size=source_image_size,
        threshold=threshold,
        device=str(device),
        batchnorm_mode=args.batchnorm_mode,
        v2_label_stats=collect_v2_label_stats(manifest, benchmark_root),
    )
    (output_dir / "per_sample_metrics.jsonl").write_text(
        "".join(json.dumps(json_safe(row), sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )
    (output_dir / "summary.json").write_text(
        json.dumps(json_safe(summary), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    write_bottleneck_table(summary, output_dir / "bottleneck_table.md")
    write_readiness_report(summary, output_dir / "training_readiness.md")
    write_contact_sheet(visual_items, output_dir / "ablation_contact_sheet.png")
    print(
        json.dumps(
            {
                "summary": str(output_dir / "summary.json"),
                "bottleneck_table": str(output_dir / "bottleneck_table.md"),
                "training_readiness": str(output_dir / "training_readiness.md"),
                "contact_sheet": str(output_dir / "ablation_contact_sheet.png"),
                "rows": len(rows),
            },
            indent=2,
        ),
        flush=True,
    )


def build_model_variant(
    prediction: ModelPrediction,
    *,
    builder: PlanarGraphBuilder,
    assignment_config: EdgeAssignmentConfig,
    repair_config: RepairConfig,
    report_config: QualityReportConfig,
    infer_assignments: bool,
    extra_repair_code: str | None = None,
) -> VariantResult:
    evidence = VectorizerEvidence(
        line_prob=prediction.line_prob,
        angle=prediction.angle,
        junction_heatmap=prediction.junction_heatmap,
        assignment_labels=None,
    )
    graph_result = builder.build(evidence)
    attributed = attribute_graph_from_logits(
        graph_result,
        prediction.assignment_logits,
        line_prob=prediction.line_prob,
        config=assignment_config,
    )
    repair = conservative_repair(
        attributed,
        line_prob=prediction.line_prob,
        config=repair_config,
        infer_assignments=infer_assignments,
    )
    repair_codes = [action.code for action in repair.actions]
    if extra_repair_code:
        repair_codes.append(extra_repair_code)
    report = build_quality_report(repair.graph, repair_actions=repair.actions, config=report_config)
    return VariantResult(
        graph=repair.graph,
        status=report.status,
        warning_codes=[warning.code for warning in report.warnings],
        repair_codes=repair_codes,
    )


def build_graph_variant(
    graph: AttributedPlanarGraph,
    *,
    report_config: QualityReportConfig,
    extra_repair_code: str,
) -> VariantResult:
    action = RepairAction(code=extra_repair_code, message=f"Eval-only {extra_repair_code}.")
    report = build_quality_report(graph, repair_actions=[action], config=report_config)
    return VariantResult(
        graph=graph,
        status=report.status,
        warning_codes=[warning.code for warning in report.warnings],
        repair_codes=[extra_repair_code],
    )


def build_oracle_evidence_variant(
    target: TargetGraph,
    *,
    builder: PlanarGraphBuilder,
    repair_config: RepairConfig,
    report_config: QualityReportConfig,
) -> VariantResult:
    rendered = render_vectorizer_evidence_from_pixels(
        pixel_vertices=target.vertices,
        edges=target.edges,
        assignments=target.assignments,
        image_size=target.image_size,
        line_width=max(1, int(round(2 * target.image_size / 768))),
        junction_sigma=max(1.5, 2.0 * target.image_size / 768),
        junction_radius=max(4.0, 4.0 * target.image_size / 768),
    )
    graph_result = builder.build(rendered.evidence)
    attributed = AttributedPlanarGraph.from_planar_result(graph_result)
    repair = conservative_repair(
        attributed,
        line_prob=rendered.evidence.line_prob,
        config=repair_config,
    )
    report = build_quality_report(repair.graph, repair_actions=repair.actions, config=report_config)
    return VariantResult(
        graph=repair.graph,
        status=report.status,
        warning_codes=[warning.code for warning in report.warnings],
        repair_codes=["oracle_vector_evidence", *[action.code for action in repair.actions]],
    )


def evaluate_variant(
    variant_result: VariantResult,
    *,
    target: TargetGraph,
    example: dict[str, Any],
    variant: str,
    threshold: float,
    artifact_mask: np.ndarray | None,
) -> tuple[GraphMetrics, dict[str, Any]]:
    metrics_obj = evaluate_graph(
        variant_result.graph.to_planar_result(),
        gt_vertices=target.vertices,
        gt_edges=target.edges,
        gt_assignments=target.assignments,
        vertex_tolerance_px=max(3.0, 5.0 * target.image_size / 768),
    )
    metrics = metrics_obj.to_dict()
    extra = compute_v2_metrics(
        variant_result.graph.to_planar_result(),
        gt_vertices=target.vertices,
        gt_edges=target.edges,
        gt_assignments=target.assignments,
        image_size=target.image_size,
        issue=str(example["issue"]),
        artifact_mask=artifact_mask,
    )
    source_counts = Counter(variant_result.graph.assignment_source)
    row = {
        "id": example["id"],
        "issue": example["issue"],
        "variant": variant,
        "status": variant_result.status,
        "warnings": variant_result.warning_codes,
        "repairs": variant_result.repair_codes,
        "threshold": threshold,
        "observed_edges": int(source_counts.get("observed", 0)),
        "unknown_edges": int(source_counts.get("unknown", 0)),
        "inferred_edges": int(source_counts.get("inferred", 0)),
        "oracle_edges": int(source_counts.get("oracle", 0)),
        **metrics,
        **extra,
    }
    row["edge_f1"] = f1(float(row["edge_precision"]), float(row["edge_recall"]))
    return metrics_obj, row


def compute_v2_metrics(
    result: PlanarGraphResult,
    *,
    gt_vertices: np.ndarray,
    gt_edges: np.ndarray,
    gt_assignments: np.ndarray,
    image_size: int,
    issue: str,
    artifact_mask: np.ndarray | None,
) -> dict[str, Any]:
    contact = boundary_contact_metrics(
        pred_vertices=result.pixel_vertices,
        gt_vertices=gt_vertices,
        gt_edges=gt_edges,
        gt_assignments=gt_assignments,
        image_size=image_size,
    )
    carriers = carrier_metrics(
        pred_vertices=result.pixel_vertices,
        pred_edges=result.edges_vertices,
        pred_assignments=result.edges_assignment,
        gt_vertices=gt_vertices,
        gt_edges=gt_edges,
        gt_assignments=gt_assignments,
    )
    artifact = artifact_false_positive_rate(
        result,
        gt_vertices=gt_vertices,
        gt_edges=gt_edges,
        artifact_mask=artifact_mask,
        image_size=image_size,
        enabled=issue in ARTIFACT_ISSUES,
    )
    return {
        **contact,
        **carriers,
        **artifact,
        "dashed_carrier_recall": carriers["carrier_recall"]
        if issue == "dashed_line_support"
        else None,
    }


def boundary_contact_metrics(
    *,
    pred_vertices: np.ndarray,
    gt_vertices: np.ndarray,
    gt_edges: np.ndarray,
    gt_assignments: np.ndarray,
    image_size: int,
    frame_tolerance_px: float | None = None,
    match_tolerance_px: float | None = None,
) -> dict[str, float | int]:
    frame_tol = frame_tolerance_px or max(3.0, 4.0 * image_size / 768)
    match_tol = match_tolerance_px or max(4.0, 6.0 * image_size / 768)
    frame = infer_square_frame(gt_vertices, gt_edges, gt_assignments, image_size)
    pred_contacts = boundary_contacts(pred_vertices, frame, frame_tol)
    gt_contacts = boundary_contacts(gt_vertices, frame, frame_tol)
    matched = match_boundary_contacts(pred_contacts, gt_contacts, frame, match_tol)
    corner_recall = match_corners(pred_vertices, frame, match_tol)
    precision = ratio(matched, len(pred_contacts))
    recall = ratio(matched, len(gt_contacts))
    return {
        "boundary_contact_precision": precision,
        "boundary_contact_recall": recall,
        "boundary_contact_f1": f1(precision, recall),
        "boundary_contact_matched": matched,
        "boundary_contact_pred": len(pred_contacts),
        "boundary_contact_gt": len(gt_contacts),
        "corner_recall": corner_recall,
    }


def boundary_contacts(
    vertices: np.ndarray,
    frame: SquareFrame,
    tolerance_px: float,
) -> list[tuple[str, float]]:
    contacts: list[tuple[str, float]] = []
    corners = np.array(
        [
            [frame.x_min, frame.y_min],
            [frame.x_max, frame.y_min],
            [frame.x_max, frame.y_max],
            [frame.x_min, frame.y_max],
        ],
        dtype=np.float32,
    )
    width = max(frame.x_max - frame.x_min, 1.0)
    height = max(frame.y_max - frame.y_min, 1.0)
    for vertex in np.asarray(vertices, dtype=np.float32):
        if np.min(np.linalg.norm(corners - vertex[None, :], axis=1)) <= tolerance_px:
            continue
        x, y = float(vertex[0]), float(vertex[1])
        candidates: list[tuple[str, float, float]] = [
            ("top", abs(y - frame.y_min), (x - frame.x_min) / width),
            ("right", abs(frame.x_max - x), (y - frame.y_min) / height),
            ("bottom", abs(frame.y_max - y), (x - frame.x_min) / width),
            ("left", abs(x - frame.x_min), (y - frame.y_min) / height),
        ]
        side, distance, coord = min(candidates, key=lambda item: item[1])
        if distance <= tolerance_px:
            contacts.append((side, float(np.clip(coord, 0.0, 1.0))))
    return contacts


def match_boundary_contacts(
    pred_contacts: list[tuple[str, float]],
    gt_contacts: list[tuple[str, float]],
    frame: SquareFrame,
    tolerance_px: float,
) -> int:
    matched = 0
    for side in ("top", "right", "bottom", "left"):
        pred = [coord for item_side, coord in pred_contacts if item_side == side]
        gt = [coord for item_side, coord in gt_contacts if item_side == side]
        if not pred or not gt:
            continue
        side_length = frame.x_max - frame.x_min if side in {"top", "bottom"} else frame.y_max - frame.y_min
        distances = np.abs(np.asarray(gt)[:, None] - np.asarray(pred)[None, :]) * max(side_length, 1.0)
        rows, cols = linear_sum_assignment(distances)
        matched += int(sum(float(distances[row, col]) <= tolerance_px for row, col in zip(rows, cols)))
    return matched


def match_corners(vertices: np.ndarray, frame: SquareFrame, tolerance_px: float) -> float:
    corners = np.array(
        [
            [frame.x_min, frame.y_min],
            [frame.x_max, frame.y_min],
            [frame.x_max, frame.y_max],
            [frame.x_min, frame.y_max],
        ],
        dtype=np.float32,
    )
    if len(vertices) == 0:
        return 0.0
    distances = np.linalg.norm(corners[:, None, :] - vertices[None, :, :], axis=2)
    return float(np.mean(np.min(distances, axis=1) <= tolerance_px))


def infer_square_frame(
    gt_vertices: np.ndarray,
    gt_edges: np.ndarray,
    gt_assignments: np.ndarray,
    image_size: int,
) -> SquareFrame:
    border_indices = np.flatnonzero(np.asarray(gt_assignments) == 2)
    if len(border_indices) == 0:
        return SquareFrame(0.0, 0.0, float(image_size - 1), float(image_size - 1))
    border_vertex_indices = sorted(
        {int(vertex) for edge_idx in border_indices for vertex in gt_edges[int(edge_idx)]}
    )
    border_vertices = np.asarray(gt_vertices, dtype=np.float32)[border_vertex_indices]
    return SquareFrame(
        x_min=float(np.min(border_vertices[:, 0])),
        y_min=float(np.min(border_vertices[:, 1])),
        x_max=float(np.max(border_vertices[:, 0])),
        y_max=float(np.max(border_vertices[:, 1])),
    )


def carrier_metrics(
    *,
    pred_vertices: np.ndarray,
    pred_edges: np.ndarray,
    pred_assignments: np.ndarray,
    gt_vertices: np.ndarray,
    gt_edges: np.ndarray,
    gt_assignments: np.ndarray,
) -> dict[str, float | int]:
    gt_carriers = derive_carriers(gt_vertices, gt_edges, gt_assignments)
    pred_carriers = derive_carriers(pred_vertices, pred_edges, pred_assignments)
    matched_gt, matched_pred = match_carriers(gt_carriers, pred_carriers)
    precision = ratio(matched_pred, len(pred_carriers))
    recall = ratio(matched_gt, len(gt_carriers))
    return {
        "carrier_precision": precision,
        "carrier_recall": recall,
        "carrier_f1": f1(precision, recall),
        "carrier_gt": len(gt_carriers),
        "carrier_pred": len(pred_carriers),
        "carrier_matched_gt": matched_gt,
        "carrier_matched_pred": matched_pred,
    }


def derive_carriers(
    vertices: np.ndarray,
    edges: np.ndarray,
    assignments: np.ndarray,
    *,
    angle_tolerance_degrees: float = 2.0,
    rho_tolerance_px: float = 4.0,
) -> list[dict[str, float]]:
    carriers: list[dict[str, float]] = []
    angle_tol = np.deg2rad(angle_tolerance_degrees)
    for edge, assignment in zip(edges, assignments):
        if int(assignment) == 2:
            continue
        p0 = vertices[int(edge[0])]
        p1 = vertices[int(edge[1])]
        length = float(np.linalg.norm(p1 - p0))
        if length <= 1e-6:
            continue
        theta, rho, t0, t1 = line_parameters(p0, p1)
        matched = False
        for carrier in carriers:
            if angle_delta(theta, carrier["theta"]) <= angle_tol and abs(rho - carrier["rho"]) <= rho_tolerance_px:
                carrier["t_min"] = min(carrier["t_min"], t0, t1)
                carrier["t_max"] = max(carrier["t_max"], t0, t1)
                carrier["length"] += length
                carrier["edges"] += 1
                matched = True
                break
        if not matched:
            carriers.append(
                {
                    "theta": theta,
                    "rho": rho,
                    "t_min": min(t0, t1),
                    "t_max": max(t0, t1),
                    "length": length,
                    "edges": 1,
                }
            )
    return carriers


def match_carriers(
    gt_carriers: list[dict[str, float]],
    pred_carriers: list[dict[str, float]],
    *,
    angle_tolerance_degrees: float = 4.0,
    rho_tolerance_px: float = 8.0,
    min_overlap_fraction: float = 0.45,
) -> tuple[int, int]:
    if not gt_carriers or not pred_carriers:
        return 0, 0
    angle_tol = np.deg2rad(angle_tolerance_degrees)
    pairs: list[tuple[int, int]] = []
    for gt_idx, gt in enumerate(gt_carriers):
        for pred_idx, pred in enumerate(pred_carriers):
            if angle_delta(gt["theta"], pred["theta"]) > angle_tol:
                continue
            if abs(gt["rho"] - pred["rho"]) > rho_tolerance_px:
                continue
            overlap = max(0.0, min(gt["t_max"], pred["t_max"]) - max(gt["t_min"], pred["t_min"]))
            gt_span = max(gt["t_max"] - gt["t_min"], 1e-6)
            if overlap / gt_span >= min_overlap_fraction:
                pairs.append((gt_idx, pred_idx))
    matched_gt: set[int] = set()
    matched_pred: set[int] = set()
    for gt_idx, pred_idx in sorted(pairs):
        if gt_idx in matched_gt or pred_idx in matched_pred:
            continue
        matched_gt.add(gt_idx)
        matched_pred.add(pred_idx)
    return len(matched_gt), len(matched_pred)


def artifact_false_positive_rate(
    result: PlanarGraphResult,
    *,
    gt_vertices: np.ndarray,
    gt_edges: np.ndarray,
    artifact_mask: np.ndarray | None,
    image_size: int,
    enabled: bool,
) -> dict[str, float | int | None]:
    if not enabled or artifact_mask is None:
        return {
            "artifact_false_positive_rate": None,
            "artifact_overlap_edges": 0,
            "artifact_non_border_edges": 0,
        }
    matched_pred_edges = matched_pred_edge_indices(
        result,
        gt_vertices=gt_vertices,
        gt_edges=gt_edges,
        image_size=image_size,
    )
    non_border_edges = [
        (edge_idx, edge, int(assignment))
        for edge_idx, (edge, assignment) in enumerate(zip(result.edges_vertices, result.edges_assignment))
        if int(assignment) != 2
    ]
    if not non_border_edges:
        return {
            "artifact_false_positive_rate": 0.0,
            "artifact_overlap_edges": 0,
            "artifact_non_border_edges": 0,
        }
    overlap_edges = 0
    for edge_idx, edge, _ in non_border_edges:
        if edge_idx in matched_pred_edges:
            continue
        edge_mask = np.zeros((image_size, image_size), dtype=np.uint8)
        p0 = result.pixel_vertices[int(edge[0])]
        p1 = result.pixel_vertices[int(edge[1])]
        cv2.line(edge_mask, point(p0), point(p1), 255, max(2, image_size // 256), cv2.LINE_AA)
        if np.any((edge_mask > 0) & artifact_mask):
            overlap_edges += 1
    return {
        "artifact_false_positive_rate": ratio(overlap_edges, len(non_border_edges)),
        "artifact_overlap_edges": overlap_edges,
        "artifact_non_border_edges": len(non_border_edges),
    }


def matched_pred_edge_indices(
    result: PlanarGraphResult,
    *,
    gt_vertices: np.ndarray,
    gt_edges: np.ndarray,
    image_size: int,
) -> set[int]:
    _, pred_to_gt, _ = match_vertices(
        gt_vertices,
        result.pixel_vertices,
        tolerance=max(3.0, 5.0 * image_size / 768),
    )
    gt_lookup = {
        (min(int(v1), int(v2)), max(int(v1), int(v2)))
        for v1, v2 in np.asarray(gt_edges, dtype=np.int64)
    }
    matched: set[int] = set()
    for pred_idx, (pred_v1, pred_v2) in enumerate(result.edges_vertices):
        if int(pred_v1) not in pred_to_gt or int(pred_v2) not in pred_to_gt:
            continue
        key = (
            min(pred_to_gt[int(pred_v1)], pred_to_gt[int(pred_v2)]),
            max(pred_to_gt[int(pred_v1)], pred_to_gt[int(pred_v2)]),
        )
        if key in gt_lookup:
            matched.add(pred_idx)
    return matched


def run_model(model: torch.nn.Module, image: np.ndarray, device: torch.device) -> ModelPrediction:
    tensor = (
        torch.from_numpy(np.asarray(image, dtype=np.uint8).copy())
        .permute(2, 0, 1)
        .unsqueeze(0)
        .float()
        .to(device)
        / 255.0
    )
    with torch.no_grad():
        outputs = model(tensor)
    return ModelPrediction(
        line_prob=torch.sigmoid(outputs["line_logits"][0, 0]).detach().cpu().numpy().astype(np.float32),
        angle=outputs["angle"][0].detach().cpu().permute(1, 2, 0).numpy().astype(np.float32),
        junction_heatmap=torch.sigmoid(outputs["junction_logits"][0, 0]).detach().cpu().numpy().astype(np.float32),
        assignment_logits=outputs["assignment_logits"][0].detach().cpu(),
    )


def mask_artifact_evidence(
    prediction: ModelPrediction,
    artifact_mask: np.ndarray,
    *,
    dilation_px: int = 2,
) -> ModelPrediction:
    mask = artifact_mask.astype(np.uint8)
    if dilation_px > 0:
        kernel = np.ones((2 * dilation_px + 1, 2 * dilation_px + 1), dtype=np.uint8)
        mask = cv2.dilate(mask, kernel, iterations=1)
    keep = mask == 0
    return replace(
        prediction,
        line_prob=np.where(keep, prediction.line_prob, 0.0).astype(np.float32),
        junction_heatmap=np.where(keep, prediction.junction_heatmap, 0.0).astype(np.float32),
    )


def apply_oracle_border_chain(
    graph: AttributedPlanarGraph,
    *,
    target: TargetGraph,
    image_size: int,
) -> AttributedPlanarGraph:
    border_indices = np.flatnonzero(target.assignments == 2)
    if len(border_indices) == 0:
        return graph

    pixel_vertices = np.asarray(graph.pixel_vertices, dtype=np.float32).copy()
    vertex_support = np.asarray(graph.vertex_support, dtype=np.float32).copy()
    snap_tolerance = max(4.0, 8.0 * image_size / 768)
    gt_to_pred: dict[int, int] = {}
    used_pred_vertices: set[int] = set()
    border_gt_vertices = sorted(
        set(int(v) for edge_idx in border_indices for v in target.edges[int(edge_idx)])
    )
    for gt_idx in border_gt_vertices:
        gt_point = target.vertices[gt_idx]
        distances = np.linalg.norm(pixel_vertices - gt_point[None, :], axis=1)
        candidates = [
            int(idx)
            for idx in np.argsort(distances)
            if float(distances[int(idx)]) <= snap_tolerance and int(idx) not in used_pred_vertices
        ]
        if candidates:
            pred_idx = candidates[0]
            pixel_vertices[pred_idx] = gt_point
            gt_to_pred[gt_idx] = pred_idx
            used_pred_vertices.add(pred_idx)
            continue
        gt_to_pred[gt_idx] = int(len(pixel_vertices))
        pixel_vertices = np.vstack([pixel_vertices, gt_point])
        vertex_support = np.concatenate([vertex_support, np.array([1.0], dtype=np.float32)])
        used_pred_vertices.add(gt_to_pred[gt_idx])

    endpoint_map = {idx: idx for idx in range(len(pixel_vertices))}
    border_points = np.asarray([target.vertices[idx] for idx in border_gt_vertices], dtype=np.float32)
    for vertex_idx, vertex in enumerate(pixel_vertices):
        distances = np.linalg.norm(border_points - vertex[None, :], axis=1)
        nearest = int(np.argmin(distances))
        if float(distances[nearest]) <= snap_tolerance:
            endpoint_map[vertex_idx] = gt_to_pred[border_gt_vertices[nearest]]

    oracle_edges: list[tuple[int, int]] = []
    for edge_idx in border_indices:
        gt_v1, gt_v2 = (int(value) for value in target.edges[int(edge_idx)])
        pred_v1 = gt_to_pred[gt_v1]
        pred_v2 = gt_to_pred[gt_v2]
        if pred_v1 == pred_v2:
            continue
        oracle_edges.append((pred_v1, pred_v2))

    edge_records: dict[tuple[int, int], dict[str, Any]] = {}

    def add_record(
        v1: int,
        v2: int,
        *,
        assignment: int,
        support: float,
        confidence: float,
        margin: float,
        source: str,
        probabilities: np.ndarray | None,
    ) -> None:
        if v1 == v2:
            return
        key = (min(int(v1), int(v2)), max(int(v1), int(v2)))
        record = {
            "edge": key,
            "assignment": int(assignment),
            "support": float(support),
            "confidence": float(confidence),
            "margin": float(margin),
            "source": source,
            "probabilities": probabilities,
        }
        previous = edge_records.get(key)
        if previous is None:
            edge_records[key] = record
            return
        previous_is_oracle = previous["source"] == "oracle"
        record_is_oracle = source == "oracle"
        if record_is_oracle and not previous_is_oracle:
            edge_records[key] = record
        elif record_is_oracle == previous_is_oracle and support > float(previous["support"]):
            edge_records[key] = record

    oracle_prob = np.zeros(4, dtype=np.float32)
    oracle_prob[2] = 1.0
    for v1, v2 in oracle_edges:
        add_record(
            v1,
            v2,
            assignment=2,
            support=1.0,
            confidence=1.0,
            margin=1.0,
            source="oracle",
            probabilities=oracle_prob,
        )

    keep = np.flatnonzero(np.asarray(graph.edges_assignment) != 2)
    for edge_idx in keep:
        old_v1, old_v2 = (int(value) for value in graph.edges_vertices[int(edge_idx)])
        probabilities = None
        if graph.assignment_probabilities is not None:
            probabilities = np.asarray(graph.assignment_probabilities[int(edge_idx)], dtype=np.float32)
        add_record(
            endpoint_map.get(old_v1, old_v1),
            endpoint_map.get(old_v2, old_v2),
            assignment=int(graph.edges_assignment[int(edge_idx)]),
            support=float(graph.edge_support[int(edge_idx)]),
            confidence=float(graph.assignment_confidence[int(edge_idx)]),
            margin=float(graph.assignment_margin[int(edge_idx)]),
            source=graph.assignment_source[int(edge_idx)],
            probabilities=probabilities,
        )

    records = list(edge_records.values())
    edges_vertices = np.asarray([record["edge"] for record in records], dtype=np.int64)
    edges_assignment = np.asarray([record["assignment"] for record in records], dtype=np.int8)
    edge_support = np.asarray([record["support"] for record in records], dtype=np.float32)
    confidence = np.asarray([record["confidence"] for record in records], dtype=np.float32)
    margin = np.asarray([record["margin"] for record in records], dtype=np.float32)
    source = [str(record["source"]) for record in records]
    probabilities = None
    if any(record["probabilities"] is not None for record in records):
        probabilities = np.asarray(
            [
                record["probabilities"]
                if record["probabilities"] is not None
                else one_hot_assignment(int(record["assignment"]))
                for record in records
            ],
            dtype=np.float32,
        )
    pixel_vertices, vertex_support, edges_vertices = compact_vertices(
        pixel_vertices,
        vertex_support,
        edges_vertices,
    )
    return attributed_graph_from_arrays(
        pixel_vertices=pixel_vertices,
        edges_vertices=edges_vertices,
        edges_assignment=edges_assignment,
        edge_support=edge_support,
        vertex_support=vertex_support,
        assignment_confidence=confidence,
        assignment_margin=margin,
        assignment_source=source,
        assignment_probabilities=probabilities,
        image_size=image_size,
        debug={**graph.debug, "oracle_border_chain": True},
    )


def apply_oracle_assignments(
    graph: AttributedPlanarGraph,
    *,
    target: TargetGraph,
    image_size: int,
) -> AttributedPlanarGraph:
    _, pred_to_gt, _ = match_vertices(
        target.vertices,
        graph.pixel_vertices,
        tolerance=max(3.0, 5.0 * image_size / 768),
    )
    gt_lookup = {
        (min(int(v1), int(v2)), max(int(v1), int(v2))): int(idx)
        for idx, (v1, v2) in enumerate(target.edges)
    }
    assignments = np.full(graph.num_edges, 3, dtype=np.int8)
    confidence = np.zeros(graph.num_edges, dtype=np.float32)
    margin = np.zeros(graph.num_edges, dtype=np.float32)
    source: list[str] = []
    probabilities = np.zeros((graph.num_edges, 4), dtype=np.float32)
    for edge_idx, (v1, v2) in enumerate(graph.edges_vertices):
        if int(v1) not in pred_to_gt or int(v2) not in pred_to_gt:
            probabilities[edge_idx, 3] = 1.0
            source.append("unknown")
            continue
        gt_key = (
            min(pred_to_gt[int(v1)], pred_to_gt[int(v2)]),
            max(pred_to_gt[int(v1)], pred_to_gt[int(v2)]),
        )
        gt_idx = gt_lookup.get(gt_key)
        if gt_idx is None:
            probabilities[edge_idx, 3] = 1.0
            source.append("unknown")
            continue
        assignment = int(target.assignments[gt_idx])
        assignments[edge_idx] = assignment
        confidence[edge_idx] = 1.0
        margin[edge_idx] = 1.0
        probabilities[edge_idx, assignment] = 1.0
        source.append("oracle")
    return attributed_graph_from_arrays(
        pixel_vertices=graph.pixel_vertices,
        edges_vertices=graph.edges_vertices,
        edges_assignment=assignments,
        edge_support=graph.edge_support,
        vertex_support=graph.vertex_support,
        assignment_confidence=confidence,
        assignment_margin=margin,
        assignment_source=source,
        assignment_probabilities=probabilities,
        image_size=image_size,
        debug={**graph.debug, "oracle_assignments": True},
    )


def oracle_topology_graph(target: TargetGraph) -> AttributedPlanarGraph:
    result = PlanarGraphResult(
        vertices_coords=np.clip(target.vertices / max(float(target.image_size - 1), 1.0), 0.0, 1.0).astype(np.float32),
        edges_vertices=target.edges.astype(np.int64),
        edges_assignment=target.assignments.astype(np.int8),
        edge_support=np.ones(len(target.edges), dtype=np.float32),
        vertex_support=np.ones(len(target.vertices), dtype=np.float32),
        pixel_vertices=target.vertices.astype(np.float32),
        debug={"oracle_topology": True},
    )
    return AttributedPlanarGraph.from_planar_result(
        result,
        assignments_from_existing_result(result),
    )


def attributed_graph_from_arrays(
    *,
    pixel_vertices: np.ndarray,
    edges_vertices: np.ndarray,
    edges_assignment: np.ndarray,
    edge_support: np.ndarray,
    vertex_support: np.ndarray,
    assignment_confidence: np.ndarray,
    assignment_margin: np.ndarray,
    assignment_source: list[str],
    assignment_probabilities: np.ndarray | None,
    image_size: int,
    debug: dict[str, Any],
) -> AttributedPlanarGraph:
    return AttributedPlanarGraph(
        vertices_coords=np.clip(pixel_vertices / max(float(image_size - 1), 1.0), 0.0, 1.0).astype(np.float32),
        edges_vertices=np.asarray(edges_vertices, dtype=np.int64).copy(),
        edges_assignment=np.asarray(edges_assignment, dtype=np.int8).copy(),
        edge_support=np.asarray(edge_support, dtype=np.float32).copy(),
        vertex_support=np.asarray(vertex_support, dtype=np.float32).copy(),
        pixel_vertices=np.asarray(pixel_vertices, dtype=np.float32).copy(),
        assignment_confidence=np.asarray(assignment_confidence, dtype=np.float32).copy(),
        assignment_margin=np.asarray(assignment_margin, dtype=np.float32).copy(),
        assignment_source=list(assignment_source),
        assignment_probabilities=None
        if assignment_probabilities is None
        else np.asarray(assignment_probabilities, dtype=np.float32).copy(),
        debug=dict(debug),
    )


def compact_vertices(
    pixel_vertices: np.ndarray,
    vertex_support: np.ndarray,
    edges_vertices: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if len(edges_vertices) == 0:
        return (
            np.empty((0, 2), dtype=np.float32),
            np.empty(0, dtype=np.float32),
            np.empty((0, 2), dtype=np.int64),
        )
    used = sorted({int(vertex) for edge in edges_vertices for vertex in edge})
    remap = {old: new for new, old in enumerate(used)}
    compacted_edges = np.asarray(
        [[remap[int(v1)], remap[int(v2)]] for v1, v2 in edges_vertices],
        dtype=np.int64,
    )
    return (
        np.asarray(pixel_vertices, dtype=np.float32)[used],
        np.asarray(vertex_support, dtype=np.float32)[used],
        compacted_edges,
    )


def one_hot_assignment(assignment: int) -> np.ndarray:
    values = np.zeros(4, dtype=np.float32)
    values[int(np.clip(assignment, 0, 3))] = 1.0
    return values


def build_summary(
    rows: list[dict[str, Any]],
    metric_items: list[tuple[str, str, GraphMetrics]],
    *,
    manifest_path: Path,
    checkpoint: Path,
    checkpoint_manifest: Path,
    checkpoint_id: str | None,
    image_size: int,
    source_image_size: int,
    threshold: float,
    device: str,
    batchnorm_mode: str,
    v2_label_stats: dict[str, Any],
) -> dict[str, Any]:
    by_variant: dict[str, Any] = {}
    by_issue_variant: dict[str, Any] = {}
    variants = sorted({variant for _, variant, _ in metric_items})
    issues = sorted({issue for issue, _, _ in metric_items})
    for variant in variants:
        variant_rows = [row for row in rows if row["variant"] == variant]
        variant_metrics = [metrics for _, item_variant, metrics in metric_items if item_variant == variant]
        by_variant[variant] = aggregate_slice(variant_rows, variant_metrics)
    for issue in issues:
        for variant in variants:
            slice_rows = [
                row for row in rows if row["issue"] == issue and row["variant"] == variant
            ]
            slice_metrics = [
                metrics
                for item_issue, item_variant, metrics in metric_items
                if item_issue == issue and item_variant == variant
            ]
            if slice_rows:
                by_issue_variant[f"{issue}/{variant}"] = aggregate_slice(slice_rows, slice_metrics)
    return {
        "schema": "cp-detector/v2-issue-ablation/v1",
        "manifest": manifest_path.as_posix(),
        "checkpoint": checkpoint.as_posix(),
        "checkpoint_manifest": checkpoint_manifest.as_posix(),
        "checkpoint_id": checkpoint_id,
        "image_size": image_size,
        "source_image_size": source_image_size,
        "threshold": threshold,
        "device": device,
        "batchnorm_mode": batchnorm_mode,
        "v2_label_stats": v2_label_stats,
        "sample_count": len({row["id"] for row in rows}),
        "row_count": len(rows),
        "variants": variants,
        "issues": issues,
        "by_variant": by_variant,
        "by_issue_variant": by_issue_variant,
        "deltas": build_deltas(by_issue_variant),
    }


def aggregate_slice(rows: list[dict[str, Any]], metrics: list[GraphMetrics]) -> dict[str, Any]:
    payload = dict(metrics_from_results(metrics))
    payload.update(row_counts(rows))
    for key in [
        "edge_f1",
        "boundary_contact_precision",
        "boundary_contact_recall",
        "boundary_contact_f1",
        "corner_recall",
        "carrier_precision",
        "carrier_recall",
        "carrier_f1",
        "dashed_carrier_recall",
        "artifact_false_positive_rate",
    ]:
        value = mean_non_null(row.get(key) for row in rows)
        if value is not None:
            payload[key] = value
    return payload


def row_counts(rows: list[dict[str, Any]]) -> dict[str, Any]:
    status_counts = Counter(str(row["status"]) for row in rows)
    warning_counts: Counter[str] = Counter()
    repair_counts: Counter[str] = Counter()
    for row in rows:
        warning_counts.update(str(item) for item in row.get("warnings", []))
        repair_counts.update(str(item) for item in row.get("repairs", []))
    return {
        "samples": len(rows),
        "status_counts": dict(sorted(status_counts.items())),
        "warning_counts": dict(sorted(warning_counts.items())),
        "repair_counts": dict(sorted(repair_counts.items())),
    }


def build_deltas(by_issue_variant: dict[str, Any]) -> dict[str, Any]:
    deltas: dict[str, Any] = {}
    grouped: dict[str, dict[str, Any]] = defaultdict(dict)
    for key, payload in by_issue_variant.items():
        issue, variant = key.split("/", 1)
        grouped[issue][variant] = payload
    for issue, variants in grouped.items():
        baseline = variants.get("issue_baseline_model")
        if not baseline:
            continue
        for variant, payload in variants.items():
            if variant == "issue_baseline_model":
                continue
            deltas[f"{issue}/{variant}"] = {
                metric: nullable_delta(payload.get(metric), baseline.get(metric))
                for metric in [
                    "edge_f1",
                    "border_f1",
                    "boundary_contact_f1",
                    "carrier_recall",
                    "artifact_false_positive_rate",
                    "assignment_accuracy",
                ]
            }
    return deltas


def collect_v2_label_stats(manifest: dict[str, Any], benchmark_root: Path) -> dict[str, Any]:
    vertex_types: Counter[str] = Counter()
    line_styles: Counter[str] = Counter()
    issues: Counter[str] = Counter()
    carrier_counts: list[int] = []
    min_edge_lengths: list[float] = []
    closest_vertex_spacings: list[float] = []
    artifact_examples = 0
    ambiguous_examples = 0
    missing_sidecars: list[str] = []
    for example in manifest.get("examples", []):
        label_rel = example.get("v2_label_sidecar")
        if not label_rel:
            missing_sidecars.append(str(example.get("id", "")))
            continue
        labels = json.loads((benchmark_root / label_rel).read_text(encoding="utf-8"))
        issues.update([str(labels.get("issue", ""))])
        vertex_types.update(str(vertex["type"]) for vertex in labels.get("vertices", []))
        carrier_counts.append(len(labels.get("carriers", [])))
        evidence = labels.get("render_evidence", {})
        line_styles.update([str(evidence.get("line_style", "unknown"))])
        if evidence.get("artifact_mask") is not None:
            artifact_examples += 1
        if bool(evidence.get("ambiguous_mv", False)):
            ambiguous_examples += 1
        spacing = labels.get("spacing", {})
        min_edge_lengths.append(float(spacing.get("min_edge_length_px", 0.0)))
        closest_vertex_spacings.append(float(spacing.get("closest_vertex_spacing_px", 0.0)))
    return {
        "examples": int(sum(issues.values())),
        "issues": dict(sorted(issues.items())),
        "vertex_types": dict(sorted(vertex_types.items())),
        "line_styles": dict(sorted(line_styles.items())),
        "artifact_examples": artifact_examples,
        "ambiguous_examples": ambiguous_examples,
        "carrier_count_min": int(min(carrier_counts)) if carrier_counts else 0,
        "carrier_count_max": int(max(carrier_counts)) if carrier_counts else 0,
        "carrier_count_mean": float(np.mean(carrier_counts)) if carrier_counts else 0.0,
        "min_edge_length_px_min": float(np.min(min_edge_lengths)) if min_edge_lengths else 0.0,
        "closest_vertex_spacing_px_min": float(np.min(closest_vertex_spacings))
        if closest_vertex_spacings
        else 0.0,
        "missing_sidecars": missing_sidecars,
    }


def write_bottleneck_table(summary: dict[str, Any], path: Path) -> None:
    columns = [
        "variant",
        "samples",
        "edge_f1",
        "border_f1",
        "boundary_contact_f1",
        "carrier_recall",
        "dashed_carrier_recall",
        "artifact_fp_rate",
        "valid_rate",
    ]
    lines = [
        "# V2 Issue Ablation Bottleneck Table",
        "",
        f"- Manifest: `{summary['manifest']}`",
        f"- Checkpoint: `{summary['checkpoint_id']}`",
        f"- Image size: `{summary['image_size']}`",
        "",
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for variant, payload in summary["by_variant"].items():
        values = [
            variant,
            str(payload.get("samples", "")),
            format_metric(payload.get("edge_f1")),
            format_metric(payload.get("border_f1")),
            format_metric(payload.get("boundary_contact_f1")),
            format_metric(payload.get("carrier_recall")),
            format_metric(payload.get("dashed_carrier_recall")),
            format_metric(payload.get("artifact_false_positive_rate")),
            format_metric(payload.get("structural_validity_rate")),
        ]
        lines.append("| " + " | ".join(values) + " |")
    lines.extend(
        [
            "",
            "## Issue Slices",
            "",
            "| issue | variant | edge_f1 | border_f1 | boundary_contact_f1 | carrier_recall | artifact_fp_rate |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for key, payload in sorted(summary["by_issue_variant"].items()):
        issue, variant = key.split("/", 1)
        lines.append(
            "| "
            + " | ".join(
                [
                    issue,
                    variant,
                    format_metric(payload.get("edge_f1")),
                    format_metric(payload.get("border_f1")),
                    format_metric(payload.get("boundary_contact_f1")),
                    format_metric(payload.get("carrier_recall")),
                    format_metric(payload.get("artifact_false_positive_rate")),
                ]
            )
            + " |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_readiness_report(summary: dict[str, Any], path: Path) -> None:
    baseline = summary["by_variant"].get("issue_baseline_model", {})
    clean = summary["by_variant"].get("clean_reference_model", {})
    oracle = summary["by_variant"].get("oracle_topology", {})
    labels = summary.get("v2_label_stats", {})
    artifact_baseline = artifact_slice(summary, "issue_baseline_model")
    artifact_oracle = artifact_slice(summary, "artifact_mask_oracle")
    lines = [
        "# V2 Training Readiness",
        "",
        "This report stops before launching any model training run.",
        "",
        "## Data/Label Setup",
        "",
        f"- V2 label sidecars: `{labels.get('examples', 0)}` examples.",
        f"- Issue slices: `{json.dumps(labels.get('issues', {}), sort_keys=True)}`.",
        f"- Vertex labels: `{json.dumps(labels.get('vertex_types', {}), sort_keys=True)}`.",
        f"- Line styles: `{json.dumps(labels.get('line_styles', {}), sort_keys=True)}`.",
        f"- Carrier count range: `{labels.get('carrier_count_min', 0)}`-`{labels.get('carrier_count_max', 0)}`.",
        f"- Minimum edge length: `{labels.get('min_edge_length_px_min', 0.0):.2f}px`.",
        "",
        "## Ablation Snapshot",
        "",
        "| slice | edge_f1 | border_f1 | boundary_contact_f1 | carrier_recall | artifact_fp_rate |",
        "| --- | --- | --- | --- | --- | --- |",
        readiness_row("clean_reference_model", clean),
        readiness_row("issue_baseline_model", baseline),
        readiness_row("artifact_slice_baseline", artifact_baseline),
        readiness_row("artifact_slice_oracle", artifact_oracle),
        readiness_row("oracle_topology", oracle),
        "",
        "## Readiness Call",
        "",
    ]
    oracle_ok = float(oracle.get("edge_f1", 0.0)) >= 0.999
    sidecars_ok = labels.get("examples", 0) > 0 and not labels.get("missing_sidecars")
    if oracle_ok and sidecars_ok:
        lines.extend(
            [
                "- Data and ablation setup are ready for human visual QA.",
                "- Stop here before training: CPLineNet-V2 heads/losses still need to be wired to consume these sidecars.",
                "- The first run should be a small local label/loss plumbing smoke, not a high-resolution GPU run.",
                "- Artifact, dashed, faint, and ambiguous-assignment slices should drive the first V2-head de-risking run.",
            ]
        )
    else:
        lines.append("- Not ready even for training setup review: fix the failed sidecar/oracle gates above first.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def artifact_slice(summary: dict[str, Any], variant: str) -> dict[str, Any]:
    keys = [
        f"{issue}/{variant}"
        for issue in ["text_false_positive", "watermark_false_positive", "guide_grid_false_positive"]
    ]
    slices = [summary["by_issue_variant"][key] for key in keys if key in summary["by_issue_variant"]]
    if not slices:
        return {}
    return {
        "samples": sum(int(item.get("samples", 0)) for item in slices),
        "edge_f1": mean_non_null(item.get("edge_f1") for item in slices),
        "border_f1": mean_non_null(item.get("border_f1") for item in slices),
        "boundary_contact_f1": mean_non_null(item.get("boundary_contact_f1") for item in slices),
        "carrier_recall": mean_non_null(item.get("carrier_recall") for item in slices),
        "artifact_false_positive_rate": mean_non_null(
            item.get("artifact_false_positive_rate") for item in slices
        ),
    }


def readiness_row(name: str, payload: dict[str, Any]) -> str:
    return (
        f"| {name} | {format_metric(payload.get('edge_f1'))} | "
        f"{format_metric(payload.get('border_f1'))} | "
        f"{format_metric(payload.get('boundary_contact_f1'))} | "
        f"{format_metric(payload.get('carrier_recall'))} | "
        f"{format_metric(payload.get('artifact_false_positive_rate'))} |"
    )


def load_target_graph(
    root: Path,
    example: dict[str, Any],
    source_image_size: int,
    image_size: int,
) -> TargetGraph:
    sidecar = json.loads((root / example["sidecar"]).read_text(encoding="utf-8"))
    vertices = np.asarray(sidecar["vertices"], dtype=np.float32)
    if source_image_size != image_size:
        vertices = vertices * ((image_size - 1) / max(float(source_image_size - 1), 1.0))
    return TargetGraph(
        vertices=vertices.astype(np.float32),
        edges=np.asarray(sidecar["edges"], dtype=np.int64),
        assignments=np.asarray(sidecar["assignments"], dtype=np.int8),
        image_size=image_size,
    )


def load_rgb(path: Path, *, image_size: int) -> np.ndarray:
    image = Image.open(path).convert("RGB")
    if image.size != (image_size, image_size):
        image = image.resize((image_size, image_size), Image.Resampling.BILINEAR)
    return np.asarray(image, dtype=np.uint8)


def load_artifact_mask(
    root: Path,
    example: dict[str, Any],
    *,
    issue: str,
    image_size: int,
) -> np.ndarray | None:
    if issue not in ARTIFACT_ISSUES:
        return None
    mask_rel = example.get("oracle_mask")
    if not mask_rel:
        return None
    image = Image.open(root / mask_rel).convert("RGB")
    if image.size != (image_size, image_size):
        image = image.resize((image_size, image_size), Image.Resampling.NEAREST)
    array = np.asarray(image, dtype=np.uint8)
    return np.any(array > 0, axis=2)


def target_line_mask(target: TargetGraph) -> np.ndarray:
    mask = np.zeros((target.image_size, target.image_size), dtype=np.uint8)
    width = max(5, int(round(6 * target.image_size / 1024)))
    for edge in target.edges:
        p0 = target.vertices[int(edge[0])]
        p1 = target.vertices[int(edge[1])]
        cv2.line(mask, point(p0), point(p1), 255, width, cv2.LINE_AA)
    return mask > 0


def write_graph_overlay(
    path: Path,
    image: np.ndarray,
    graph: AttributedPlanarGraph,
    *,
    label: str,
) -> None:
    canvas = Image.fromarray(image.copy())
    draw = ImageDraw.Draw(canvas)
    vertices = graph.pixel_vertices
    for edge_idx, edge in enumerate(graph.edges_vertices):
        assignment = int(graph.edges_assignment[edge_idx])
        color = ASSIGNMENT_COLORS.get(assignment, ASSIGNMENT_COLORS[3])
        width = 4 if assignment == 2 else 2
        p0 = tuple(float(value) for value in vertices[int(edge[0])])
        p1 = tuple(float(value) for value in vertices[int(edge[1])])
        draw.line([p0, p1], fill=color, width=width)
    for x, y in vertices:
        draw.ellipse((float(x) - 2, float(y) - 2, float(x) + 2, float(y) + 2), fill=(28, 160, 80))
    draw.rectangle((0, 0, canvas.width, 24), fill=(255, 255, 255))
    draw.text((6, 6), label, fill=(20, 20, 20), font=ImageFont.load_default())
    path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(path)


def write_contact_sheet(items: list[dict[str, Any]], path: Path, *, cell_width: int = 260) -> None:
    if not items:
        return
    columns = [
        ("issue_image", "Issue"),
        ("issue_baseline_model", "Baseline"),
        ("artifact_mask_oracle", "Artifact Oracle"),
        ("oracle_border_chain", "Border Oracle"),
        ("oracle_vector_evidence", "Evidence Oracle"),
        ("target", "Target"),
    ]
    gap = 12
    label_height = 58
    footer_height = 20
    cell_height = cell_width + label_height + footer_height
    sheet_width = gap + len(columns) * (cell_width + gap)
    sheet_height = gap + len(items) * (cell_height + gap)
    sheet = Image.new("RGB", (sheet_width, sheet_height), "white")
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default()
    for row_idx, item in enumerate(items):
        y = gap + row_idx * (cell_height + gap)
        draw.text((gap, y), f"{item['issue']} / {item['id']}", fill=(20, 20, 20), font=font)
        for col_idx, (key, label) in enumerate(columns):
            x = gap + col_idx * (cell_width + gap)
            if item.get(key) is None:
                cell = Image.new("RGB", (cell_width, cell_width), (248, 248, 248))
                ImageDraw.Draw(cell).text((10, 10), "n/a", fill=(120, 120, 120), font=font)
            else:
                cell = Image.open(item[key]).convert("RGB")
            cell.thumbnail((cell_width, cell_width), Image.Resampling.LANCZOS)
            top = y + label_height
            sheet.paste(cell, (x, top))
            draw.text((x, top + cell.height + 3), label, fill=(80, 80, 80), font=font)
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


def line_parameters(p0: np.ndarray, p1: np.ndarray) -> tuple[float, float, float, float]:
    direction = np.asarray(p1, dtype=np.float64) - np.asarray(p0, dtype=np.float64)
    theta = float(np.arctan2(direction[1], direction[0]) % np.pi)
    unit = np.array([np.cos(theta), np.sin(theta)], dtype=np.float64)
    normal = np.array([-np.sin(theta), np.cos(theta)], dtype=np.float64)
    rho = float(np.dot(normal, p0))
    if rho < 0:
        rho = -rho
        theta = float((theta + np.pi) % np.pi)
        unit = -unit
    t0 = float(np.dot(unit, p0))
    t1 = float(np.dot(unit, p1))
    return theta, rho, t0, t1


def angle_delta(a: float, b: float) -> float:
    delta = abs((a - b) % np.pi)
    return float(min(delta, np.pi - delta))


def point(point_array: np.ndarray) -> tuple[int, int]:
    return (int(round(float(point_array[0]))), int(round(float(point_array[1]))))


def ratio(numerator: int | float, denominator: int | float) -> float:
    return float(numerator / denominator) if denominator else 0.0


def f1(precision: float, recall: float) -> float:
    return 2.0 * precision * recall / (precision + recall) if precision + recall else 0.0


def mean_non_null(values: Iterable[Any]) -> float | None:
    filtered = [float(value) for value in values if value is not None]
    if not filtered:
        return None
    return float(np.mean(filtered))


def nullable_delta(value: Any, baseline: Any) -> float | None:
    if value is None or baseline is None:
        return None
    return float(value) - float(baseline)


def format_metric(value: Any) -> str:
    if value is None:
        return ""
    return f"{float(value):.4f}"


def resolve_path(path: Path) -> Path:
    return path if path.is_absolute() else REPO_ROOT / path


def json_safe(value: Any) -> Any:
    if isinstance(value, Path):
        return value.as_posix()
    if isinstance(value, np.ndarray):
        return [json_safe(item) for item in value.tolist()]
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    return value


if __name__ == "__main__":
    main()
